### ISSUE TITLE
Making a quiz on a different webpage

### ISSUE THREAD

**Issue by chrisgdclarke** [ALPSquid/quizlib#1]
Great quiz, however I'm struggling to make another quiz on the same website but a different webpage.

What are the changes needed to make this happen e.g. how do i specify the id and answers of another quiz? Can I do this in the same javascript file (main.js) as the first quiz or if I need a separate file, what changes to the code do I need to make.  Any assistance much appreciated!

Chris

**Comment by chrisgdclarke** [comment]
I've tried:

`window.onload = function() {
    quiz = new Quiz('quiz-modalities', [ 'a', 'd' ]);
};
window.onload = function() {
    quiz = new Quiz('quiz-chest', [ 'b', 'b' ]);
};`

but only the quiz-chest is working...

**Comment by ALPSquid** [comment]
Hi!

You've got two main options really. 
1. Create a separate script for each page containing page specific logic. Then you can simply have the quiz-chest code in one file and the quiz-modalities code in another file and load them on the respective page.

2. If you want just one script, you'll need different variables for each quiz to stop one being overwritten.

For example:
```
var quizModalities;
var quizChest;

window.onload = function() {
    // Load the quizzes that exist on the page.
    if (document.getElementById("quiz-modalities") != null) {
	quizModalities = new Quiz('quiz-modalities', [
	    '42',
	    'b',
	    ['b', 'c', 'd']
	]);
    }
	
    if (document.getElementById("quiz-chest") != null) {
        quizChest = new Quiz('quiz-chest', [
	    '1',
	    'b',
	    ['b', 'c', 'd']
	]);
    }
};
```

Note that you will need to edit your answer handling to get the current quiz. If you're using the same function for both quizzes, a simple option with the least amount of editing is to pass the active quiz instance to the function:

```
var quiz;

function showResults(activeQuiz) {
    quiz = activeQuiz;
    // Rest of showResults logic here.
}
```
Then in your answer button HTML, edit the `showResults `call in `onclick ` to pass the respective quiz variable to the showResults function. For example:
`<button type="button" onclick="showResults(quizChest);">Check Answers</button>`

Let me know if that helps!

**Comment by chrisgdclarke** [comment]
Thank you so much!  I'm pretty new to coding so I did your first method and it's working great.

If I learn more javascript I'll try your second method to see if it works.  It would be really useful to put an example of your second method (maybe with 3 separate quizzes on the same html page) so I could see how the code works in that situation.

Thank you again.

**Comment by ALPSquid** [comment]
Glad you got it working!

I've changed the highResults callback slightly to make it easier to implement multiple quizzes on a single page and created an example which can be found at https://github.com/ALPSquid/quizlib/tree/master/example/multi-quiz
You can grab the release at https://github.com/ALPSquid/quizlib/releases/tag/1.0.1


Thanks for your feedback!
